### ISSUE TITLE
Move project to use go modules

### ISSUE THREAD

**Issue by skonto** [openshift-knative/serverless-operator#380]
Should we move this to use go modules, what are the impliciations?

**Comment by markusthoemmes** [comment]
We should do this once we're using an upstream version that has go modules too. IIRC that was done through 0.15 so we likely should make the switch soonish.
It may have implications on our usage of operator-sdk as only recent versions of that use go modules but IIRC we can't simply upgrade because their handling in webhooks has changed quite a bit.

**Comment by navidshaikh** [comment]
AFAIK a project using go modules could safely vendor the non-go-modules based deps. 
Besides, pinned version of operator-sdk in knative-operator is `v0.10.1` which is using go modules.

**Comment by markusthoemmes** [comment]
This is done!
